### ISSUE TITLE
Maximum duration should be renamed to slow treshold

### ISSUE THREAD

**Issue by mvorisek** [ergebnis/phpunit-slow-test-detector#388]
IMHO "slow treshold" is much more clearer than "maximum duration" which generaly means timeout, ie, the test terminated after such time.

**Comment by localheinz** [comment]
@mvorisek 

I chose maximum duration because the extension measures the duration of a test and then determines whether a test is slow or not. I found the naming and reference to speed trap confusing and misleading, because I am looking for slow tests, not tests that are fast.

I kept support for the `@slowThreshold` annotation to make it easier for people willing to switch over from [`johnkary/phpunit-speedtrap`](https://github.com/johnkary/phpunit-speedtrap) and will eventually remove it.
